### ISSUE TITLE
Use cleaner page filenames

### ISSUE THREAD

**Issue by ErikBoesen** [english-now/english-now.github.io#43]
The one that always bothers me is /semi-intensive-and-intensive-programs. I think it could be much better if it was just /intensive. There are other instances that you can probably find for yourself where there are annoyingly long links. /english-for-workplace-communication -> /workplace, etc. You get the picture.

While you're at it, I've always hated how /contact-us isn't just /contact. Might want to add a redirect for that though.

**Comment by AndrewLester** [comment]
Since I already added the jekyll-redirect-from plugin, I think it would be possible to change those urls to new ones, while keeping support for the old url. Then we can phase out the old links at a later time. 

Usage: [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from#usage)

**Comment by ErikBoesen** [comment]
Ah yes, forgot about that. Definitely give that a shot then.
